version: '3.7'

services:
  db:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ~/apps/mongo:/data/db
    networks:
      - unig4construction

networks:
  unig4construction:
    external: true
